### ISSUE TITLE
ModLauncher下同一个mod包含coremod和fmlmod

### ISSUE THREAD

**Issue by Ranpoes** [xfl03/CoreModTutor#11]
LaunchWrapper时期，可通过设置manifest的FMLCorePluginContainsFMLMod为true来使一个mod同时被当做coremod与普通mod去加载，然而此配置似乎在ModLauncher下不再生效。
    观察到本指导提到"从Forge 1.13.2-25.0.216开始，可以使用Forge来加载无论是否包含普通Mod的ModLauncher CoreMod"，而且万用皮肤补丁在高版本下单一mod兼顾了coremod与普通mod，请问是如何做到的呢？

**Comment by Ranpoes** [comment]
补充一下问题背景：我试图写一个coremod来获得所有被加载mod的classpath（ModLauncher下区别于URLClassLoader的TransformingClassLoader代理接管了transform阶段的类加载行为，使得不能简单通过ucp来获得所有mod的classpath，不过我通过mixin的rootContainer解决了），并希望通过forge netty和服务端通信，单一coremod不能完成这样的需求。

**Comment by ZekerZhayard** [comment]
这是准备写反作弊么。。。

Minecraft 1.17 之后 modlauncher 使用了 Java 的模块系统，把整个游戏生命周期分成了四个 Module Layer：Boot Layer、Service Layer、Plugin Layer、Game Layer，你可以通过 Java 自身的模块 API 获取对应 Moudle Layer 下的所有 Module

**Comment by Ranpoes** [comment]
1.17后针对已有的模块化来实现这个需求的建议是好的，但仅对1.13~1.16版本范围内，让一个mod同时作为fmlmod和coremod的问题没有得到解决。观察forge源码中ModsFolderLocator的scanMods方法：
``` List<Path> excluded = ModDirTransformerDiscoverer.allExcluded();```
它会将所有coremod的jar包classpth排除，使得游戏主进程启动后、fml模组加载时，FMLLoader中的loadingModList不会包含任何coremod（事实上coremod的toml信息都不会被解析），疑似没有什么注解和配置可以绕过这个设定。观察万用皮肤补丁的源码，应该也是独立实现了一个SPI代理了各个版本的coremod加载实现做到两者兼顾的吧。

**Comment by ZekerZhayard** [comment]
> 观察万用皮肤补丁的源码，应该也是独立实现了一个SPI代理了各个版本的coremod加载实现做到两者兼顾的吧。

CustomSkinLoader 使用了 FML 提供的使用 JavaScript 编写 CoreMod 的 API，想要 FML 识别 JS CoreMod，这个 Mod 必须依附在包含 mods.toml 的普通 Mod 里；  

如果想利用 modlauncher 提供的 `cpw.mods.modlauncher.api.ITransformationService` 你还需要单独实现一个 `net.minecraftforge.forgespi.locating.IModLocator` 以把自身加入进去（这两个 SPI 接口是可以放在同一个 jar 里的，只需要在 `ITransformationService` 的 `initialize` 阶段执行一下 `ModDirTransformerDiscoverer.getExtraLocators().add(<core mod path>);` 就行）。

**Comment by Ranpoes** [comment]
这个建议非常有用，IModLocator的SPI可以向```net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer```的locatorList追加新的实现，这里可以自定义控制mod的扫描与加载行为！
